# Домашнее задание 3 "Продвинутая линейная алгебра".

Уровень 0:
Придумайте матрицы, которые обладают следующими свойствами:

a) Диагональная, ортогональная, но не единичная(!)

b) Верхнетреугольная, ортогональная

c) Нижнетреугольная, ортогональная

d) Матрица, у которой определитель = 1, и все элементы не равны 0

P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

Найдите собственные значения и собственные вектора матриц:

m = np.array([[2, 2],
              [1, 3]])
print(m)

In [1]:
import numpy as np
import pylab as pl
import warnings

from matplotlib import pyplot as plt
from scipy import linalg
from sklearn.datasets import load_digits
from sklearn.decomposition import TruncatedSVD
from sklearn.ensemble import RandomForestClassifier
warnings.filterwarnings("ignore")

In [22]:
# a) Диагональная, ортогональная, но не единичная(!)
A = np.diag([1,-1])
A
# AT = A.transpose()
# A.dot(AT)


array([[ 1,  0],
       [ 0, -1]])

In [47]:
# b) Верхнетреугольная, ортогональная
B = np.array([[1, 0],[0, -1]])
B
# BT = B.transpose()
# B.dot(BT)

array([[1, 0],
       [0, 1]])

In [49]:
#c) Нижнетреугольная, ортогональная
C = np.array([[1, 0],[0, -1]])
C
# CT = C.transpose()
# C.dot(CT)

array([[1, 0],
       [0, 1]])

In [13]:
CT = C.transpose()
C.dot(CT)

array([[1, 1],
       [1, 2]])

In [35]:
#d) Матрица, у которой определитель = 1, и все элементы не равны 0
m = np.array([[2, 1], [1, 1]])
det = np.linalg.det(m)
print(m)
print(det)

[[2 1]
 [1 1]]
1.0


# Уровень 1:
Найдите спектральное разложение матрицы:

m = np.array([[1, 2],
              [2,3]])
print(m)


In [55]:
from sklearn.decomposition import PCA
from numpy import linalg as LA

In [79]:
m = np.array([[1, 2],
              [2, 3]])
print(m)

[[1 2]
 [2 3]]


m = St @ D @ S 
s - ортогональная матрица
D - диагональная матрица
St - транспонированная S


In [86]:
v, w = np.linalg.eigh(m)

In [87]:
w

array([[-0.85065081,  0.52573111],
       [ 0.52573111,  0.85065081]])

In [88]:
v

array([-0.23606798,  4.23606798])

In [90]:
D = np.diag(v)
D

array([[-0.23606798,  0.        ],
       [ 0.        ,  4.23606798]])

In [91]:
S = w.T

In [92]:
S

array([[-0.85065081,  0.52573111],
       [ 0.52573111,  0.85065081]])

In [93]:
S.T

array([[-0.85065081,  0.52573111],
       [ 0.52573111,  0.85065081]])

In [95]:
np.dot(S.T, S)

array([[ 1.0000000e+00, -1.2127222e-17],
       [-1.2127222e-17,  1.0000000e+00]])

In [97]:
np.dot(np.dot(S.T, D), S)

array([[1., 2.],
       [2., 3.]])