# Домашнее задание «Библиотека numpy. Вычислительные задачи»


## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [14]:
N = int(input('Введите колчиество элементов: '))
a = np.arange(N-1, -1, -1) 
a


Введите колчиество элементов: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [25]:
N = int(input('Введите колчиество элементов: '))
print(np.diag(np.arange(N-1, -1, -1), k = 0))
print(f'Сумма значений на дигонали: {sum(np.arange(N-1, -1, -1))}')

Введите колчиество элементов: 10
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма значений на дигонали: 45


## Задание 3
Решите систему уравнений:

4x + 2y + z = 4 

x + 3y = 12

5y + 4z = -3

In [41]:
matrix_1 = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]]) 
matrix_2 = np.array([4, 12, -3])

In [33]:
from numpy import linalg

In [42]:
u = np.linalg.solve(matrix_1, matrix_2)
print(u)

[ 0.46666667  3.84444444 -5.55555556]


# Задача 4 
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [43]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [50]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [55]:
next_user_length = np.linalg.norm(next_user_stats)


In [57]:
for user in users_stats:
    user_length = np.linalg.norm(user)
    print(np.dot(user, next_user_stats) / (next_user_length * user_length))

0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.3999999999999999
0.0
0.0
0.9486832980505138
0.0
0.0


In [73]:
def cosine( users_stats, next_user_stats ):
   
    # длина вектора нового пользователя
    next_user_length = np.linalg.norm(next_user_stats)
    
    max_cosine = 0 #максимальное значение косинуса
    i = 0 #вспомогательная переменная для хранения индекса очередного пользователя
    j = 0 #индекс максимально похожего пользователя 
    for user in users_stats:
        user_length = np.linalg.norm(user) #длина вектора user
        if np.dot(user, next_user_stats) / (next_user_length * user_length) > max_cosine:
            max_cosine = np.dot(user, next_user_stats) / (next_user_length * user_length)
            j = i
        i += 1
    return (print(f'Индекс максимально похожего пользователя {j}, со значением косинуса {max_cosine}'))
    

In [74]:
cosine( users_stats, next_user_stats )

Индекс максимально похожего пользователя 7, со значением косинуса 0.9486832980505138
